### ISSUE TITLE
Project directory structure

### ISSUE THREAD

**Issue by jsalahov** [Rostlab/JS16_ProjectB_Group6#24]
Hello there, people. As you should have noticed, tests are failing :smile_cat: 
Reason is directory structure has changed, so tests can't "require" modules.
So the question is : Is this the final directory structure of the project?

**Comment by asesselmann** [comment]
No, because we are not even near to starting our real task (implementing the support vector machine).

The files in the weka folder worked with the provided dummy data,
the files in the api-handler folder work with the actual data of Project A's database.

The structure will keep changing, maybe its best if we notify you, when we have the final (or even nearly final) structure.

Maybe one of the others has a better idea?

**Comment by jsalahov** [comment]
If there will be any commit that changes the directories or breaks the tests in any other way, assign the pull request to me. I'll modify the tests if needed and then merge your pull request.

**Comment by subburamr** [comment]
@CavidSalahov  Just as a headsup, due to change in project [deliverable](https://github.com/Rostlab/JS16_ProjectB_Group6/issues/17#issuecomment-197341471) we would be removing the svm(no longer being implemented) and weka(was just used for preliminary task) folders from our final deliverable

The attached image is likely to be our final project structure. So you can make changes to the tests accordingly. For now, we will retain the weka folder to ensure the build doesn't fail.

![project_structure](https://cloud.githubusercontent.com/assets/9434543/13857459/4f82927a-ec7a-11e5-9281-ce49a1ca1189.png)

**Comment by jsalahov** [comment]
Well, you can also delete the contents of the spec folder, as they also became irrelevant. Build should fail then

**Comment by jsalahov** [comment]
@subburamr Is it safe to delete everything that is not pictured here? :smiling_imp:

**Comment by subburamr** [comment]
Closing this as #64 contains the final project structure

**Comment by ThuyNganTran** [comment]
I added a new directory for the PLOD of the houses (or other stats) so the final project structure is not up-to-date anymore. As for now, only a csv file, a .js file containing minor code and a node package are inside so no real tests are necessary though.

**Comment by jsalahov** [comment]
@ThuyNganTran It is safe to change the directory structure, as tests are not relevant now
